### ISSUE TITLE
Buffering behavior and size?

### ISSUE THREAD

**Issue by tmm1** [djherbis/stream#4]
From the README:

>This is done by writing to a "File" interface which buffers the input so it can be read at any time from many independent readers.

I can see that a `bytes.Buffer` is used as the underlying buffer in memfs.go, and readers maintain their own offset into the buffer's byte slice and read from it directly.

This means `Read` is never called on the `bytes.Buffer`, essentially making it an unbounded buffer that contains all the data ever written to it. Is that accurate?

**Comment by djherbis** [comment]
That is correct, stream is intended to store the entire byte stream so it can be 'joined' by readers later and they still get the whole stream.

I have (yet another) library which handles the case where you want old, unreferenced data to 'fall off' the buffer: [bufit](https://github.com/djherbis/bufit).

In bufit, you can have multiple readers for your data, and new readers can join at any time just like stream. However in bufit, once data is read by all the readers that are currently active, that part of the buffer is dropped.
